services:
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    networks:
      - mern
    restart: unless-stopped
    
  backend:
    build: ./backend 
    ports:
      - 5050:5050
    
    networks:
      - mern
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    
  mongo:
    image: mongo:6
    ports:
      - 27017:27017
    networks:
      - mern
    volumes:
      - mongo-data:/data/db 
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped


networks:
  mern:
    driver: bridge

volumes:
  mongo-data: 
    driver: local
    

  

